name: konfig-revalidate-portal
on:
  push:
    branches:
      - master
jobs:
  konfig-revalidate-portal:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1.10.0
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in "~/.npm" on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.CLI_VERSION }}
      - name: Install Konfig CLI
        run: npm install -g konfig-cli@$CLI_VERSION
      - name: Revalidate Portal
        run: konfig revalidate-portal -o groundxai -r groundx-sdks